function buildConcallPrompt(transcriptText) {
  return [
    'You are a deterministic financial research extraction engine.',
    'Analyze the earnings call transcript below and return ONLY valid JSON.',
    'Do not add markdown, comments, code fences, or any non-JSON text.',
    'Use only the transcript content. Do not hallucinate or infer external facts.',
    'Extract verbatim management commitments when possible.',
    'If something is not explicitly mentioned, return an empty array for that field.',
    '',
    'IMPORTANT:',
    '- Return ONLY valid JSON.',
    '- Do not include markdown.',
    '- Do not wrap in backticks.',
    '- Do not add explanation.',
    '- Output must be raw JSON.',
    '',
    'Return JSON exactly in this schema:',
    '{',
    '  "company": string,',
    '  "quarter": string,',
    '  "financial_sentiment": "positive" | "neutral" | "cautious" | "negative",',
    '  "confidence_level": "high" | "medium" | "low",',
    '  "key_highlights": [string],',
    '  "risks_and_concerns": [string],',
    '  "management_commitments": [string],',
    '  "guidance_outlook": [string],',
    '  "analyst_focus_areas": [string]',
    '}',
    '',
    'Bullet points must be concise and investor-grade.',
    '',
    'TRANSCRIPT START',
    transcriptText,
    'TRANSCRIPT END',
    '',
    'IMPORTANT:',
    '- Output COMPLETE valid JSON.',
    '- Do not wrap in markdown.',
    '- Ensure all brackets and arrays are properly closed.',
    '- Do not stop mid-output.',
    '- Return only raw JSON.',
  ].join('\n');
}

module.exports = {
  buildConcallPrompt,
};
